version: '3.8'

services:
  production:
    profiles: [production]
    image: eugeniusmario/myna-english:latest
    container_name: myna-english
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt/live/mynaenglish.com/fullchain.pem:/home/node/app/cert/server.cert
      - /etc/letsencrypt/live/mynaenglish.com/privkey.pem:/home/node/app/cert/server.key
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production