name: Deploy Next.js to GCP with Docker - Production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install

      - name: Build Next.js application
        run: |
          npm run build

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_IMAGE_NAME }}:latest \
            . --no-cache

      - name: Tag Docker image
        run: docker tag ${{ secrets.DOCKER_IMAGE_NAME }}:latest ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build docker-compose.yml
        run: |
          sed "s/DOCKER_IMAGE_NAME/${{secrets.DOCKERHUB_USERNAME}}\/${{secrets.DOCKER_IMAGE_NAME}}/g" docker-compose-template.yml > docker-compose.yml
          sed -i "s/DOCKER_CONTAINER_NAME/${{secrets.DOCKER_CONTAINER_NAME}}/g" docker-compose.yml

      - name: scp into GCP instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GCE_INSTANCE_IP }}
          username: ${{ secrets.GCE_SSH_USERNAME }}
          key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.GCE_SSH_USERNAME }}/"

      - name: SSH into GCP instance and deploy Next.js
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCE_INSTANCE_IP }}
          username: ${{ secrets.GCE_SSH_USERNAME }}
          key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
          script: |
            docker compose -f /home/${{ secrets.GCE_SSH_USERNAME }}/docker-compose.yml --profile production down
            docker compose -f /home/${{ secrets.GCE_SSH_USERNAME }}/docker-compose.yml --profile production up --pull always -d

            docker image prune -f -a